### ISSUE TITLE
Exception while drawing: "QuotaExceeded"

### ISSUE THREAD

**Issue by RoryBlyth** [csells/vertex_ai_quickdraw#2]
**Issue:** It was working. I was drawing a sheep (see attached). It was about to guess... and then it died with this exception: **"QuotaExceeded (Online prediction request quota exceeded for gemini-1.5-flash. Please try again later with backoff.)"**

![AC44DE30-9FC9-4BBD-9167-617706FC2E53](https://github.com/user-attachments/assets/9ef36354-6f6b-4b81-b5eb-4e8509382c9e)
![A67CC2E4-F47F-4E19-8844-52F6C27417C6](https://github.com/user-attachments/assets/e607a02f-d6fb-4915-8548-db77b1c7bb8f)

**Comment by RoryBlyth** [comment]
This was my fault. I think. Have to go up my quota for Vertex usage in the Google Cloud Console.

**Comment by csells** [comment]
the quota thing isn't the problem; the fact that the app crashed when you hit your quota is the problem. that's a bug that should be fixed.
